// Code generated for Sozdy go-microservices
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Sozdy/go-microservices/order/internal/model"
	"github.com/Sozdy/go-microservices/order/internal/service/order"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function for the type OrderService
func (_mock *OrderService) CancelOrder(ctx context.Context, orderUUID uuid.UUID) (*order.CancelOrderOut, error) {
	ret := _mock.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 *order.CancelOrderOut
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*order.CancelOrderOut, error)); ok {
		return returnFunc(ctx, orderUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *order.CancelOrderOut); ok {
		r0 = returnFunc(ctx, orderUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.CancelOrderOut)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *OrderService_Expecter) CancelOrder(ctx interface{}, orderUUID interface{}) *OrderService_CancelOrder_Call {
	return &OrderService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, orderUUID)}
}

func (_c *OrderService_CancelOrder_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *OrderService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_CancelOrder_Call) Return(cancelOrderOut *order.CancelOrderOut, err error) *OrderService_CancelOrder_Call {
	_c.Call.Return(cancelOrderOut, err)
	return _c
}

func (_c *OrderService_CancelOrder_Call) RunAndReturn(run func(ctx context.Context, orderUUID uuid.UUID) (*order.CancelOrderOut, error)) *OrderService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type OrderService
func (_mock *OrderService) CreateOrder(ctx context.Context, in *order.CreateOrderIn) (*order.CreateOrderOut, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *order.CreateOrderOut
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *order.CreateOrderIn) (*order.CreateOrderOut, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *order.CreateOrderIn) *order.CreateOrderOut); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.CreateOrderOut)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *order.CreateOrderIn) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *order.CreateOrderIn
func (_e *OrderService_Expecter) CreateOrder(ctx interface{}, in interface{}) *OrderService_CreateOrder_Call {
	return &OrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, in)}
}

func (_c *OrderService_CreateOrder_Call) Run(run func(ctx context.Context, in *order.CreateOrderIn)) *OrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *order.CreateOrderIn
		if args[1] != nil {
			arg1 = args[1].(*order.CreateOrderIn)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_CreateOrder_Call) Return(createOrderOut *order.CreateOrderOut, err error) *OrderService_CreateOrder_Call {
	_c.Call.Return(createOrderOut, err)
	return _c
}

func (_c *OrderService_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, in *order.CreateOrderIn) (*order.CreateOrderOut, error)) *OrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type OrderService
func (_mock *OrderService) GetOrder(ctx context.Context, orderUUID uuid.UUID) (*model.Order, error) {
	ret := _mock.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Order, error)); ok {
		return returnFunc(ctx, orderUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Order); ok {
		r0 = returnFunc(ctx, orderUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *OrderService_Expecter) GetOrder(ctx interface{}, orderUUID interface{}) *OrderService_GetOrder_Call {
	return &OrderService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderUUID)}
}

func (_c *OrderService_GetOrder_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *OrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_GetOrder_Call) Return(order1 *model.Order, err error) *OrderService_GetOrder_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *OrderService_GetOrder_Call) RunAndReturn(run func(ctx context.Context, orderUUID uuid.UUID) (*model.Order, error)) *OrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function for the type OrderService
func (_mock *OrderService) PayOrder(ctx context.Context, in *order.PayOrderOrderIn) (*order.PayOrderOrderOut, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *order.PayOrderOrderOut
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *order.PayOrderOrderIn) (*order.PayOrderOrderOut, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *order.PayOrderOrderIn) *order.PayOrderOrderOut); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.PayOrderOrderOut)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *order.PayOrderOrderIn) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *order.PayOrderOrderIn
func (_e *OrderService_Expecter) PayOrder(ctx interface{}, in interface{}) *OrderService_PayOrder_Call {
	return &OrderService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, in)}
}

func (_c *OrderService_PayOrder_Call) Run(run func(ctx context.Context, in *order.PayOrderOrderIn)) *OrderService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *order.PayOrderOrderIn
		if args[1] != nil {
			arg1 = args[1].(*order.PayOrderOrderIn)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_PayOrder_Call) Return(payOrderOrderOut *order.PayOrderOrderOut, err error) *OrderService_PayOrder_Call {
	_c.Call.Return(payOrderOrderOut, err)
	return _c
}

func (_c *OrderService_PayOrder_Call) RunAndReturn(run func(ctx context.Context, in *order.PayOrderOrderIn) (*order.PayOrderOrderOut, error)) *OrderService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
