// Code generated for Sozdy go-microservices
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Sozdy/go-microservices/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewPartRepository creates a new instance of PartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartRepository {
	mock := &PartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PartRepository is an autogenerated mock type for the PartRepository type
type PartRepository struct {
	mock.Mock
}

type PartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartRepository) EXPECT() *PartRepository_Expecter {
	return &PartRepository_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function for the type PartRepository
func (_mock *PartRepository) GetPart(ctx context.Context, uuid string) (*model.Part, error) {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Part, error)); ok {
		return returnFunc(ctx, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Part); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type PartRepository_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *PartRepository_Expecter) GetPart(ctx interface{}, uuid interface{}) *PartRepository_GetPart_Call {
	return &PartRepository_GetPart_Call{Call: _e.mock.On("GetPart", ctx, uuid)}
}

func (_c *PartRepository_GetPart_Call) Run(run func(ctx context.Context, uuid string)) *PartRepository_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_GetPart_Call) Return(part *model.Part, err error) *PartRepository_GetPart_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *PartRepository_GetPart_Call) RunAndReturn(run func(ctx context.Context, uuid string) (*model.Part, error)) *PartRepository_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function for the type PartRepository
func (_mock *PartRepository) ListParts(ctx context.Context, partUUIDs []string, partType model.PartType) ([]*model.Part, error) {
	ret := _mock.Called(ctx, partUUIDs, partType)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, model.PartType) ([]*model.Part, error)); ok {
		return returnFunc(ctx, partUUIDs, partType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, model.PartType) []*model.Part); ok {
		r0 = returnFunc(ctx, partUUIDs, partType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, model.PartType) error); ok {
		r1 = returnFunc(ctx, partUUIDs, partType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type PartRepository_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - partUUIDs []string
//   - partType model.PartType
func (_e *PartRepository_Expecter) ListParts(ctx interface{}, partUUIDs interface{}, partType interface{}) *PartRepository_ListParts_Call {
	return &PartRepository_ListParts_Call{Call: _e.mock.On("ListParts", ctx, partUUIDs, partType)}
}

func (_c *PartRepository_ListParts_Call) Run(run func(ctx context.Context, partUUIDs []string, partType model.PartType)) *PartRepository_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 model.PartType
		if args[2] != nil {
			arg2 = args[2].(model.PartType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PartRepository_ListParts_Call) Return(parts []*model.Part, err error) *PartRepository_ListParts_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartRepository_ListParts_Call) RunAndReturn(run func(ctx context.Context, partUUIDs []string, partType model.PartType) ([]*model.Part, error)) *PartRepository_ListParts_Call {
	_c.Call.Return(run)
	return _c
}
