// Code generated for Sozdy go-microservices
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Sozdy/go-microservices/order/internal/model/ports/inventory"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewInventoryClient creates a new instance of InventoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryClient {
	mock := &InventoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InventoryClient is an autogenerated mock type for the InventoryClient type
type InventoryClient struct {
	mock.Mock
}

type InventoryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryClient) EXPECT() *InventoryClient_Expecter {
	return &InventoryClient_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function for the type InventoryClient
func (_mock *InventoryClient) GetPart(ctx context.Context, partUUID uuid.UUID) (*inventory.Part, error) {
	ret := _mock.Called(ctx, partUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *inventory.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*inventory.Part, error)); ok {
		return returnFunc(ctx, partUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *inventory.Part); ok {
		r0 = returnFunc(ctx, partUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventory.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, partUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InventoryClient_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type InventoryClient_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - partUUID uuid.UUID
func (_e *InventoryClient_Expecter) GetPart(ctx interface{}, partUUID interface{}) *InventoryClient_GetPart_Call {
	return &InventoryClient_GetPart_Call{Call: _e.mock.On("GetPart", ctx, partUUID)}
}

func (_c *InventoryClient_GetPart_Call) Run(run func(ctx context.Context, partUUID uuid.UUID)) *InventoryClient_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InventoryClient_GetPart_Call) Return(part *inventory.Part, err error) *InventoryClient_GetPart_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *InventoryClient_GetPart_Call) RunAndReturn(run func(ctx context.Context, partUUID uuid.UUID) (*inventory.Part, error)) *InventoryClient_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function for the type InventoryClient
func (_mock *InventoryClient) ListParts(ctx context.Context, req *inventory.ListPartsRequest) (*inventory.ListPartsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 *inventory.ListPartsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *inventory.ListPartsRequest) (*inventory.ListPartsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *inventory.ListPartsRequest) *inventory.ListPartsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventory.ListPartsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *inventory.ListPartsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InventoryClient_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type InventoryClient_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - req *inventory.ListPartsRequest
func (_e *InventoryClient_Expecter) ListParts(ctx interface{}, req interface{}) *InventoryClient_ListParts_Call {
	return &InventoryClient_ListParts_Call{Call: _e.mock.On("ListParts", ctx, req)}
}

func (_c *InventoryClient_ListParts_Call) Run(run func(ctx context.Context, req *inventory.ListPartsRequest)) *InventoryClient_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *inventory.ListPartsRequest
		if args[1] != nil {
			arg1 = args[1].(*inventory.ListPartsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InventoryClient_ListParts_Call) Return(listPartsResponse *inventory.ListPartsResponse, err error) *InventoryClient_ListParts_Call {
	_c.Call.Return(listPartsResponse, err)
	return _c
}

func (_c *InventoryClient_ListParts_Call) RunAndReturn(run func(ctx context.Context, req *inventory.ListPartsRequest) (*inventory.ListPartsResponse, error)) *InventoryClient_ListParts_Call {
	_c.Call.Return(run)
	return _c
}
