// Code generated for Sozdy go-microservices
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Sozdy/go-microservices/order/internal/model/ports/payment"
	mock "github.com/stretchr/testify/mock"
)

// NewPaymentClient creates a new instance of PaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentClient {
	mock := &PaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PaymentClient is an autogenerated mock type for the PaymentClient type
type PaymentClient struct {
	mock.Mock
}

type PaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentClient) EXPECT() *PaymentClient_Expecter {
	return &PaymentClient_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type PaymentClient
func (_mock *PaymentClient) PayOrder(ctx context.Context, req *payment.PayOrderRequest) (*payment.PayOrderResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *payment.PayOrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *payment.PayOrderRequest) (*payment.PayOrderResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *payment.PayOrderRequest) *payment.PayOrderResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.PayOrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *payment.PayOrderRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentClient_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type PaymentClient_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req *payment.PayOrderRequest
func (_e *PaymentClient_Expecter) PayOrder(ctx interface{}, req interface{}) *PaymentClient_PayOrder_Call {
	return &PaymentClient_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, req)}
}

func (_c *PaymentClient_PayOrder_Call) Run(run func(ctx context.Context, req *payment.PayOrderRequest)) *PaymentClient_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *payment.PayOrderRequest
		if args[1] != nil {
			arg1 = args[1].(*payment.PayOrderRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PaymentClient_PayOrder_Call) Return(payOrderResponse *payment.PayOrderResponse, err error) *PaymentClient_PayOrder_Call {
	_c.Call.Return(payOrderResponse, err)
	return _c
}

func (_c *PaymentClient_PayOrder_Call) RunAndReturn(run func(ctx context.Context, req *payment.PayOrderRequest) (*payment.PayOrderResponse, error)) *PaymentClient_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
